name: Build and Deploy
on:
  push:
    paths: ["dist/**"]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder that the build-storybook script generates files.
          target-folder: docs # The folder that we serve our Storybook files from
      - name: Add CNAME 🔧
        run: |
          npm run set-subdomain
